export const ITEMS_POLL_START = 'ITEMS_POLL_START';
export const ITEMS_POLL_STOP = 'ITEMS_POLL_STOP';
export const ITEMS_FETCH = 'ITEMS_FETCH';
export const ITEMS_ADD = 'ITEMS_ADD';
export const ITEMS_NAME_SEARCH = 'ITEMS_NAME_SEARCH';
export const ITEMS_QUALITY_FILTER = 'ITEMS_QUALITY_FILTER';
